/**
 * markable - make non-English Markdown plain text markable
 * Copyright (c) 2026, Guxi11. (MIT Licensed)
 * https://github.com/hbhde/markable
 */

/**
 * DO NOT EDIT THIS FILE
 * The code in this file is generated from files in ./src/
 */

(function (global, factory) {
  typeof exports === 'object' && typeof module !== 'undefined' ? module.exports = factory() :
  typeof define === 'function' && define.amd ? define(factory) :
  (global = global || self, global.markable = factory());
}(this, (function () { 'use strict';

  /**
   * Helpers
   */
  var caret = /(^|[^\[])\^/g;

  function edit(regex) {
    regex = regex.source;
    var obj = {
      replace: function replace(name, val) {
        val = val.source;
        val = val.replace(caret, '$1');
        regex = regex.replace(name, val);
        return obj;
      },
      replaceAllByDict: function replaceAllByDict(dict) {
        for (var key in dict) {
          var name = key,
              val = dict[key];
          val = val.source;
          val = val.replace(caret, '$1');
          regex = regex.replace(RegExp(name, 'g'), val);
        }

        return obj;
      },
      getRegex: function getRegex() {
        return new RegExp(regex);
      }
    };
    return obj;
  }

  var helpers = {
    edit: edit
  };

  /**
   * Symbols
   * Supported Languages: Chinese
   *
   * Keys are regex patterns used to match placeholders in rules.js source.
   * Special regex chars in keys must be escaped (e.g. =\\*= for literal =*=).
   */
  var symbols = {
    '=`=': /`·/,
    '=~=': /~～/,
    '=\\*=': /\*＊/,
    '=#=': /#＃/,
    '={=': /「/,
    '=}=': /」/,
    '=<=': /<《〈/,
    '=>=': />》〉/,
    '=:=': /:：/,
    '=!=': /!！/,
    '=_=': /_——/,
    '=\\$=': /\$¥/,
    '=\\-=': /\-－/,
    '=\\+=': /\+＋/,
    '="=': /"\u201c\u201d/,
    "='=": /'\u2018\u2019/,
    '=\\\\\\[=': /\[【/,
    '=\\\\\\]=': /\]】/,
    '=\\\\\\(=': /\(（/,
    '=\\\\\\)=': /\)）/,
    '=\\\\\\|=': /\|｜/,
    '=\\\\\\.=': /\.。/
  };
  var symbols_1 = symbols;

  var edit$1 = helpers.edit;
  /**
   * Block-Level Grammar
   */

  var block = {
    newline: /^\n+/,
    heading: /^ {0,3}([=#=]{1,6})(?:\s|$)(([^\n]*)(?:\n|$))/,
    fences: /^ {0,3}([=`=]{3,}(?=[^\n]*\n)|[=~=]{3,})([^\n]*)\n(?:|([\s\S]*?)\n)(?: {0,3}\1[=`=]* *(?:\n+|$)|$)/,
    hr: /^ {0,3}([-\uff0d]{3,}|[=*=]{3,}|[=_=]{3,}) *(?:\n+|$)/,
    blockquote: /^ {0,3}[=>=]+(([^\n]*)(?:\n|$))/,
    listquote: /^ *bull ?blockquote/,
    table: /^ *([\|｜].+)\n *([\|｜][ ]*[=:=]?[-\uff0d]+[=:=]?[ ]*)+[\|｜]?[ ]*(?:\n((?:.*[\|｜].*(?:\n|$))*)\n*|$)/,
    text: /^[^\n]+/
  };
  block.bullet = /(?:[=*=+]|[-\uff0d]|\d{1,9}[=\.=])/;
  block.listquote = edit$1(block.listquote).replace('bull', block.bullet).replace('blockquote', block.blockquote).getRegex();
  /**
   * Inline-Level Grammar
   */

  var inline = {
    link: /^[=!=]?[=\[=](label)[=\]=][=\(=]\s*(href)(?:\s+(title))?\s*[=\)=]/,
    reflink: /^[=!=]?[=\[=](label)[=\]=][=\[=](id)[=\]=]/,
    linkdefinition: /^[=\[=](id)[=\]=][=:=]\s*(href)(?:\s+(title))?/,
    strong: /^[=*=]{2}((?:[^=*=]|[=*=](?![=*=]))+)[=*=]{2}|^[=_=]{2}((?:[^=_=]|[=_=](?![=_=]))+)[=_=]{2}/,
    em: /^[=*=]((?:[^=*=])+)[=*=]|^[=_=]((?:[^=_=])+)[=_=]/,
    strikethrough: /^[=~=]{2}((?:[^=~=]|[=~=](?![=~=]))+)[=~=]{2}/,
    code: /^([=`=]+)([^=`=]|[^=`=][\s\S]*?[^=`=])\1(?![=`=])/,
    text: /^([=`=]+|[^=`=])(?:[\s\S]*?(?:(?=[\\<!=\[==`=*\uff0a~\uff5e]|\b_|$)|[^ ](?= {2,}\n))|(?= {2,}\n))/
  };
  inline._label = /(?:[=\[=][^=\[==\]=]*[=\]=]|\\.|[=`=][^=`=]*[=`=]|[^=\[==\]=\\=`=])*?/;
  inline._href = /<(?:\\[<>]?|[^\s<>\\])*>|[^\s\x00-\x1f]*/;
  inline._title = /[="=](?:\\[="=]?|[^="=\\])*[="=]|[='=](?:\\[='=]?|[^='=\\])*[='=]|[=\(=](?:\\[=\)=]?|[^)\\])*[=\)=]/;
  inline._id = /(?!\s*[=\]=])((?:\\[=\[==\]=]?|[^=\[==\]=\\])+)/;
  inline.link = edit$1(inline.link).replace('label', inline._label).replace('href', inline._href).replace('title', inline._title).getRegex();
  inline.reflink = edit$1(inline.reflink).replace('label', inline._label).replace('id', inline._id).getRegex();
  inline.linkdefinition = edit$1(inline.linkdefinition).replace('id', inline._id).replace('href', inline._href).replace('title', inline._title).getRegex();
  /**
   * Grammar Translate Symbols
   */

  [block, inline].map(function (grammer) {
    for (var key in grammer) {
      grammer[key] = edit$1(grammer[key]).replaceAllByDict(symbols_1).getRegex();
    }
  });
  var rules = {
    block: block,
    inline: inline
  };

  var inline$1 = rules.inline;
  /**
   * InlineTranslator
   */

  var InlineTranslator_1 = /*#__PURE__*/function () {
    function InlineTranslator() {
      this.rules = inline$1;
    }

    InlineTranslator.translate = function translate(src) {
      var translator = new InlineTranslator();
      return translator.translate(src);
    };

    var _proto = InlineTranslator.prototype;

    _proto.translate = function translate(src) {
      var dest = '',
          cap,
          left,
          right;

      while (src) {
        // link
        if (cap = this.rules.link.exec(src)) {
          src = src.substring(cap[0].length);
          left = cap[0].substring(0, cap[0].indexOf(cap[1])).replace(/！/, '!').replace(/【/, '[');
          right = cap[0].substring(cap[0].indexOf(cap[1]) + cap[1].length).replace(/】/, ']').replace(/（/, '(').replace(/）/, ')').replace(/[\u201c\u201d]/g, '"').replace(/[\u2018\u2019]/g, "'");
          dest += left + this.translate(cap[1]) + right;
          continue;
        } // reflink


        if (cap = this.rules.reflink.exec(src)) {
          src = src.substring(cap[0].length);
          left = cap[0].substring(0, cap[0].indexOf(cap[1])).replace(/【/, '[');
          right = cap[0].substring(cap[0].indexOf(cap[1]) + cap[1].length).replace(/【/, '[').replace(/】/g, ']');
          dest += left + this.translate(cap[1]) + right;
          continue;
        } // linkdefinition


        if (cap = this.rules.linkdefinition.exec(src)) {
          src = src.substring(cap[0].length);
          dest += cap[0].replace(/【/, '[').replace(/】/, ']').replace(/：/, ':').replace(/[\u201c\u201d]/g, '"').replace(/[\u2018\u2019]/g, "'");
          continue;
        } // strong (bold)


        if (cap = this.rules.strong.exec(src)) {
          src = src.substring(cap[0].length);
          var inner = cap[1] || cap[2];
          var marker = cap[1] ? '**' : '__';
          dest += marker + this.translate(inner) + marker;
          continue;
        } // em (italic)


        if (cap = this.rules.em.exec(src)) {
          src = src.substring(cap[0].length);

          var _inner = cap[1] || cap[2];

          var _marker = cap[1] ? '*' : '_';

          dest += _marker + this.translate(_inner) + _marker;
          continue;
        } // strikethrough


        if (cap = this.rules.strikethrough.exec(src)) {
          src = src.substring(cap[0].length);
          dest += '~~' + this.translate(cap[1]) + '~~';
          continue;
        } // code


        if (cap = this.rules.code.exec(src)) {
          src = src.substring(cap[0].length);
          dest += cap[0].replace(/·/g, '`');
          continue;
        } // text


        if (cap = this.rules.text.exec(src)) {
          src = src.substring(cap[0].length);
          dest += cap[0];
          continue;
        }
      }

      return dest;
    };

    return InlineTranslator;
  }();

  var block$1 = rules.block;
  /**
   * Block Translator
   */

  var Translator_1 = /*#__PURE__*/function () {
    function Translator() {
      this.rules = block$1;
      this.dest = '';
    }

    Translator.translate = function translate(src) {
      var translator = new Translator();
      return translator.translate(src);
    };

    var _proto = Translator.prototype;

    _proto.translate = function translate(src) {
      // preprocessing
      src = src.replace(/\r\n|\r/g, '\n').replace(/\t/g, '    ');
      var cap, left;

      while (src) {
        // newline
        if (cap = this.rules.newline.exec(src)) {
          src = src.substring(cap[0].length);
          this.dest += cap[0];
        } // heading


        if (cap = this.rules.heading.exec(src)) {
          src = src.substring(cap[0].length);
          var hashes = cap[1].replace(/＃/g, '#');
          this.dest += hashes + cap[0].substring(cap[1].length, cap[0].indexOf(cap[2])) + InlineTranslator_1.translate(cap[2]);
          continue;
        } // fences


        if (cap = this.rules.fences.exec(src)) {
          src = src.substring(cap[0].length);
          this.dest += cap[0].replace(/[·]{3}/g, '```').replace(/[～]{3}/g, '~~~');
          continue;
        } // hr


        if (cap = this.rules.hr.exec(src)) {
          src = src.substring(cap[0].length);
          var rule = cap[1].replace(/－/g, '-').replace(/＊/g, '*').replace(/——/g, '__');
          this.dest += cap[0].replace(cap[1], rule);
          continue;
        } // table


        if (cap = this.rules.table.exec(src)) {
          src = src.substring(cap[0].length);
          this.dest += cap[0].replace(/｜/g, '|').replace(/：/g, ':').replace(/－/g, '-');
          continue;
        } // blockquote or listquote


        if ((cap = this.rules.blockquote.exec(src)) || (cap = this.rules.listquote.exec(src))) {
          src = src.substring(cap[0].length);
          left = cap[0].substring(0, cap[0].indexOf(cap[1])).replace(/[》〉]/g, '>');
          this.dest += left + InlineTranslator_1.translate(cap[1]);
          continue;
        } // text


        if (cap = this.rules.text.exec(src)) {
          src = src.substring(cap[0].length);
          this.dest += InlineTranslator_1.translate(cap[0]);
        }
      }

      return this.dest;
    };

    return Translator;
  }();

  /**
   * Markable
   */

  function markable(src) {
    // throw error in case of non string input
    if (typeof src === 'undefined' || src === null) {
      throw new Error('markable(): input parameter is undefined or null');
    }

    if (typeof src !== 'string') {
      throw new Error('markable(): input parameter is of type ' + Object.prototype.toString.call(src) + ', string expected');
    }

    return Translator_1.translate(src);
  }
  /**
   * Expose
   */

  var markable_1 = markable;

  return markable_1;

})));
